### ISSUE TITLE
You forgot to commit the code :) 

### ISSUE THREAD

**Issue by kmcquade** [matthewmaribojoc/learn-vue-tabs#1]
Hey @matthewmaribojoc,

Going through your blog post. It looks like you forgot to put your code in this repository.

 https://learnvue.co/2019/12/building-reusable-components-in-vuejs-tabs/

**Comment by alexander-albul** [comment]
😢

**Comment by matthewmaribojoc** [comment]
Hey, everyone sorry about this - the link in the post was wrong! [Here](https://github.com/matthewmaribojoc/learn-vue-tab) is the proper repo.
